package businessLayer;

/**
 * @author Gorkem
 *
 */
public enum DoctorDiscipline {
	ALLERGIST, ANESTHESIOLOGIST, CARDIOLOGIST, DERMATOLOGIST,
	GASTROENTEROLOGIST,ONCOLOGIST, NEPHROLOGIST, NEUROLOGIST,
	OBSTETRICIAN, GYNECLOGIST, OPTHALMOLOGIST, PATHOLOGIST ,
	PEDIATRICIAN, PODIATRIST, PSYCHIATRIST, UROLOGIST 
}
