package businessLayer;

/**
 * @author Gorkem
 *
 */
public enum Medicine {
	SYNTHROID, CRESTOR, VENTOLIN_HFA,
	NEXIUM, ADVAIR, DISKUS, VYVANSE, 
	LYRICA, JANUVIA, HYDROCODONE, LISIOPRIL,
	OTRIVINE, SUDAFED, ASPIRIN, TIMOLOL,
	FENTANYL, XANAX, ADDERALL, DEXEDRINE
}
